INSERT INTO DataWareHouse.dbo.DIM_FechaNacimiento
(FechaNacimiento,Dia,Mes,Annio)
SELECT DISTINCT FECHA_DE_NACIMIENTO AS FechaNacimiento
	,DAY(FECHA_DE_NACIMIENTO) AS Dia
	,MONTH(FECHA_DE_NACIMIENTO) AS Mes
	,YEAR (FECHA_DE_NACIMIENTO) AS Annio
FROM DL_Contratos.dbo.DL_Contratistas
WHERE FECHA_DE_NACIMIENTO IS NOT NULL 