-- DL_Contratos.dbo.DL_Contratos definition

-- Drop table

-- DROP TABLE DL_Contratos.dbo.DL_Contratos;

CREATE TABLE DL_Contratos.dbo.DL_Contratos (
	NUM_PROCESO nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NUM_CONTRATO nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GERENCIA_AREA nvarchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SUBGERENCIA nvarchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OBJETO_CONTRACTUAL nvarchar(700) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TIPO_GASTO_1 nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TIPO_GASTO_2 nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRESUPUESTO nvarchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NUM_CDP_1 int NULL,
	NUM_CDP_2 int NULL,
	VALOR_CDP_1 int NULL,
	VALOR_CDP_2 int NULL,
	COD_TIPO_CONTRATO int NULL,
	TIPO_CONTRATO nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	VALOR_INICIAL int NULL,
	HONORARIOS_MENSUALES int NULL,
	ID_CONTRATISTA int NULL,
	FECHA_RP date NULL,
	VALOR_RP_1 int NULL,
	VALOR_RP_2 int NULL,
	FECHA_SUSCRIPCION date NULL,
	FECHA_INICIO date NULL,
	FECHA_TERMINACION date NULL,
	NOMBRE_SUPERVISOR nvarchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);